### ISSUE TITLE
Sample IDs in Clinical data  - Taylor et.al.

### ISSUE THREAD

**Issue by varsha090597** [Syksy/curatedPCaData#28] opened 2021-10-06 18:28 UTC
Clinical data file has sample IDs which aren't uniform with the naming convention for Taylor et. al. Clinical data script needs to be re-run.

**Comment by Syksy** [comment] 2021-10-06 20:52
I'm working on it, as the gex and cna matrices of Taylor have already been re-generated for these names. The GEOquery downloads for GSM sample data are failing at the moment for reasons unknown, but this should be fixed soon.

**Comment by Syksy** [comment] 2021-10-06 20:54
This is a duplicate of issue #27

**Closed as completed by Syksy** 2021-10-06 20:54 UTC
